/* scrip 1 */

insert into makmodtrimlevel values(337, 'PASSATVART', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'PASSATVART', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'PASSATVART', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'PASSATVART', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'PASSATVART', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'PASSATVART', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'GOLF', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'GOLF', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'GOLF', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'GOLF', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'GOLF', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'GOLF', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'JETTA', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'JETTA', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'JETTA', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'JETTA', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'JETTA', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'JETTA', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'PASSAT', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'PASSAT', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'PASSAT', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'PASSAT', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'PASSAT', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'PASSAT', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'TOUAREG', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'TOUAREG', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'TOUAREG', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'TOUAREG', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'TOUAREG', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'TOUAREG', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'TIGUAN', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'TIGUAN', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'TIGUAN', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'TIGUAN', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'TIGUAN', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'TIGUAN', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'SCIROCCO', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'SCIROCCO', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'SCIROCCO', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'SCIROCCO', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'SCIROCCO', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'SCIROCCO', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'SHARAN', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'SHARAN', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'SHARAN', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'SHARAN', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'SHARAN', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'SHARAN', 'CARAT', 'EN', 'Carat');

insert into makmodtrimlevel values(337, 'BEETLE', 'BLUEMOTION');
insert into lanmakmodtrimlevel values(337, 'BEETLE', 'BLUEMOTION', 'EN', 'BlueMotion');
insert into makmodtrimlevel values(337, 'BEETLE', 'TRENDLINE');
insert into lanmakmodtrimlevel values(337, 'BEETLE', 'TRENDLINE', 'EN', 'Trendline');
insert into makmodtrimlevel values(337, 'BEETLE', 'CARAT');
insert into lanmakmodtrimlevel values(337, 'BEETLE', 'CARAT', 'EN', 'Carat');





/* GOLF */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3170,'FR','GOLFCONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'GOLF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3170, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3170,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3170,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3170,'2015',1,'GRANDE','vw_golf_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3171,'FR','GOLFCONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'GOLF',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3171, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3171,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3171,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3171,'2015',1,'GRANDE','vw_golf_GRANDE.png','PAYSAGE',2015,'Exterieur');


Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3172,'FR','GOLFCONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'GOLF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3172, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3172,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3172,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3172,'2015',1,'GRANDE','vw_golf_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3173,'FR','GOLFCONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'GOLF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3173, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3173,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3173,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3173,'2015',1,'GRANDE','vw_golf_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3174,'FR','GOLFCONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'GOLF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3174, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3174,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3174,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3174,'2015',1,'GRANDE','vw_golf_GRANDE.png','PAYSAGE',2015,'Exterieur');



/* TIGUAN */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3180,'FR','TIGUANCONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TIGUAN',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3180, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3180,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3180,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3180,'2015',1,'GRANDE','vw_tiguan_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3181,'FR','TIGUANCONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TIGUAN',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3181, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3181,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3181,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3181,'2015',1,'PETITE','vw_tiguan2_s_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3182,'FR','TIGUANCONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TIGUAN',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3182, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3182,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3182,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3182,'2015',1,'GRANDE','vw_tiguan_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3183,'FR','TIGUANCONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TIGUAN',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3183, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3183,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3183,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3183,'2015',1,'GRANDE','vw_tiguan_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3184,'FR','TIGUANCONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TIGUAN',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3184, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3184,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3184,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3184,'2015',1,'GRANDE','vw_tiguan_GRANDE.png','PAYSAGE',2015,'Exterieur');


/* JETTA */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3190,'FR','JETTACONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'JETTA',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3190, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3190,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3190,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3190,'2015',1,'GRANDE','vw_jetta_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3191,'FR','JETTACONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'JETTA',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3191, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3191,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3191,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3191,'2015',1,'GRANDE','vw_jetta_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3192,'FR','JETTACONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'JETTA',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3192, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3192,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3192,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3192,'2015',1,'GRANDE','vw_jetta_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3193,'FR','JETTACONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'JETTA',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3193, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3193,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3193,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3193,'2015',1,'GRANDE','vw_jetta_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3194,'FR','JETTACONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'JETTA',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3194, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3194,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3194,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3194,'2015',1,'GRANDE','vw_jetta_GRANDE.png','PAYSAGE',2015,'Exterieur');

/* SCIROCCO */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3200,'FR','SCIROCCOCONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'SCIROCCO',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3200, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3200,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3200,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3200,'2015',1,'GRANDE','vw_scirocco_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3201,'FR','SCIROCCOCONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'SCIROCCO',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3201, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3201,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3201,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3201,'2015',1,'GRANDE','vw_scirocco_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3202,'FR','SCIROCCOCONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'SCIROCCO',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3202, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3202,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3202,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3202,'2015',1,'GRANDE','vw_scirocco_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3203,'FR','SCIROCCOCONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'SCIROCCO',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3203, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3203,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3203,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3203,'2015',1,'GRANDE','vw_scirocco_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3204,'FR','SCIROCCOCONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'SCIROCCO',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3204, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3204,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3204,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3204,'2015',1,'GRANDE','vw_scirocco_GRANDE.png','PAYSAGE',2015,'Exterieur');


/* TOUAREG */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3210,'FR','TOUAREGCONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TOUAREG',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3210, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3210,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3210,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3210,'2015',1,'GRANDE','vw_touareg_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3211,'FR','TOUAREGCONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TOUAREG',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3211, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3211,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3211,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3211,'2015',1,'GRANDE','vw_touareg_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3213,'FR','TOUAREGCONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TOUAREG',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3213, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3213,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3213,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3213,'2015',1,'GRANDE','vw_touareg_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3214,'FR','TOUAREGCONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TOUAREG',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3214, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3214,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3214,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3214,'2015',1,'GRANDE','vw_touareg_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3215,'FR','TOUAREGCONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'TOUAREG',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3215, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3215,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3215,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3215,'2015',1,'GRANDE','vw_touareg_GRANDE.png','PAYSAGE',2015,'Exterieur');



/* BEETLE */
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3220,'FR','BEETLECONFLNTSI14BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3220, 'EN', '1.4 TSI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3220,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3200,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3220,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3221,'FR','BEETLECONFLNTSI14DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),119,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3221, 'EN', '1.4 TSI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3221,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3221,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,37400,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3221,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3222,'FR','BEETLECONFLNTDI16BMV6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3222, 'EN', '1.6 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3222,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3222,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,32850,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3222,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3223,'FR','BEETLECONFLNTDI16DSG7','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',120,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),104,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3223, 'EN', '1.6 TDI ACT BlueMotion Technology DSG 7');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3223,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3223,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,34380,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3223,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3224,'FR','BEETLECONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3224, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3224,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3224,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3224,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (3225,'FR','BEETLECONFLNTDI20BVM6','EUR',to_date('23/04/2015','DD/MM/RR'),null,337,'BEETLE',null,null,'D','A',null,null,null,null,null,'3','VP','03','D','COUP',150,null,'ACTIF','BLUEMOTION',null,to_date('23/04/2015','DD/MM/RR'),107,null,null,null,2015,null,null,'ORFI',to_date('23/04/2015','DD/MM/RR'),null);
insert into LANVARIANT values (3225, 'EN', '2.0 TDI ACT BlueMotion Technology BVM 6');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3225,'2015',to_date('01/01/15','DD/MM/RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3225,'2015',1,to_date('01/01/15','DD/MM/RR'),'EUR',null,35050,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (3225,'2015',1,'GRANDE','vw_beetle_GRANDE.png','PAYSAGE',2015,'Exterieur');


/* scrip 2 */


insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (338, 'PASSAT', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'PASSAT', 'SLOAN','1','ORFI',null,null,null);
insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'PASSAT', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'PASSAT', 'SLOAN','1','ORFI',null,null,null);
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','PASSAT', 'EN','PASSAT');
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values (337 ,'337', 'PASSAT', '0');
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3158,'GB','PASSAT','EUR',sysdate,'337','PASSAT','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3158','EN','PASSAT TRENDLINE');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3158,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3158,1,1,sysdate,'EUR',null,'28000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3158','1','1','GRANDE','vw_passat_GRANDE.png','PAYSAGE','2015','Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3159,'GB','PASSAT','EUR',sysdate,'337','PASSAT','','','CARAT','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3159','EN','PASSAT CARAT');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3159,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3159,1,1,sysdate,'EUR',null,'32000',null,null,'ORFI',null,null);

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3160,'GB','PASSATJETTA','EUR',sysdate,'337','PASSAT','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3160','EN','PASSAT JETTA');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3160,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3160,1,1,sysdate,'EUR',null,'32000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3160','1','3','GRANDE','vw_jetta_GRANDE.png','PAYSAGE','2016','Exterieur');

insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'TIGUAN', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','TIGUAN', 'EN','Tiguan');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'TIGUAN', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'TIGUAN', '0');
Insert into MAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE) values (337,'TIGUAN','TRENDLINE');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3161,'GB','TIGUAN','EUR',sysdate,'337','TIGUAN','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3161','EN','Jetta');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3161,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3161,1,1,sysdate,'EUR',null,'32000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3161','1','4','GRANDE','vw_jetta_GRANDE.png','PAYSAGE','2017','Exterieur');

Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3161','1','4','GRANDE','vw_tiguan2_GRANDE.png','PAYSAGE','2017','Exterieur');
insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'TOUAREG', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','TOUAREG', 'EN','Touareg');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'TOUAREG', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'TOUAREG', '0');
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3162,'GB','TOUAREG','EUR',sysdate,'337','TOUAREG','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3162','EN','Touareg trend line');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3162,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3162,1,1,sysdate,'EUR',null,'32000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3162','1','5','GRANDE','vw_touareg2_GRANDE.png','PAYSAGE','2018','Exterieur');
insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'SCIROCCO', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','SCIROCCO', 'EN','Scirocco');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'SCIROCCO', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'SCIROCCO', '0');
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3163,'GB','SCIROCCO','EUR',sysdate,'337','SCIROCCO','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3163','EN','Scirocco trend line');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3163,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3163,1,1,sysdate,'EUR',null,'35000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3163','1','6','GRANDE','vw_scirocco_GRANDE.png','PAYSAGE','2021','Exterieur');
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3164,'GB','TIGUANS','EUR',sysdate,'337','TIGUAN','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3164','EN','Tiguan S trend line');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3164,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3164,1,1,sysdate,'EUR',null,'65000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3164','1','7','GRANDE','vw_tiguan_s_GRANDE.png','PAYSAGE','2015','Exterieur');
Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3165,'GB','PASSATCC','EUR',sysdate,'337','PASSAT','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3165','EN','Passat CC');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3165,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3165,1,1,sysdate,'EUR',null,'60000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3165','1','8','GRANDE','cutout_volkswagen_cc_GRANDE.png','PAYSAGE','2016','Exterieur');

insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'BEETLE', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','BEETLE', 'EN','Beetle');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'BEETLE', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'BEETLE', '0');
Insert into MAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE) values (337,'BEETLE','TRENDLINE');
Insert into LANMAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE,LANCODE,MMTLIBELLE) values (337,'BEETLE','TRENDLINE','EN','Trendline');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3166,'GB','BEETLE','EUR',sysdate,'337','BEETLE','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3166','EN','Beetle');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3166,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3166,1,1,sysdate,'EUR',null,'30000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3166','1','9','GRANDE','vw_beetle_GRANDE.png','PAYSAGE','2017','Exterieur');

insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'VENTO', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','VENTO', 'EN','Vento');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'VENTO', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'VENTO', '0');
Insert into MAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE) values (337,'VENTO','TRENDLINE');
Insert into LANMAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE,LANCODE,MMTLIBELLE) values (337,'VENTO','TRENDLINE','EN','Trendline');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3167,'GB','VENTO','EUR',sysdate,'337','VENTO','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3167','EN','Vento');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3167,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3167,1,1,sysdate,'EUR',null,'30000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3167','1','10','GRANDE','vw_vento_GRANDE.png','PAYSAGE','2018','Exterieur');


insert into MAKMODEL (MAKID, MMOCODE, MMOSERVICEDISTANCEUNIT, MMOSERVICEDISTANCEINTERVAL, MMOSERVICETIMEINTERVAL, MMODTSTART, MMODTEND, MMOTYPEVEHICLE, MMOREGINSPECTMODEL, MMOTYPERBP, MMOTYPEVEHICLEFEE, MMOSPECCONST, MMOCONSTMACH, MMOSEGMENT, MMOINDUSMAT, MMOVEHICLECATEG, MMODTUPDATE, UTICODEUPDATE, MMOYEAR, MMOFLAGREGISTRED, MMOFLAGGENERALPURPOSE, MMORATECODE, MMOASSETSEGMENT, MMOASSETDETAILTYPE, MMOASSETTYPE)values (337, 'JETTA', '', null, null, null, null, '', '', '', '', '', '', '', '', '', null, '', null, null, null, '', '', '', '');
Insert into LANMAKMODEL (MAKID,MMOCODE,LANCODE,MMOLIBELLE) values ('337','JETTA', 'EN','Jetta');
Insert into MAKMODTPG (MAKID,MMOCODE,TPGCODE,MTPFLAGRETURN,UTICODE,MTPDTUPDATE,MTPDTSTART,MTPDTEND) values ('337', 'JETTA', 'SLOAN','1','ORFI',null,null,null);
Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR ' ,'337', 'JETTA', '0');
Insert into MAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE) values (337,'JETTA','TRENDLINE');
Insert into LANMAKMODTRIMLEVEL (MAKID,MMOCODE,MMTCODE,LANCODE,MMTLIBELLE) values (337,'JETTA','TRENDLINE','EN','Trendline');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,MAKID,MMOCODE,VARENERGYTYPE,VARBODYTYPE,MMTCODE,VARCARBON,ACACODE,NAPCODE) values (3160,'GB','JETTA','EUR',sysdate,'337','JETTA','','','TRENDLINE','','','');
Insert into LANVARIANT (VARID,LANCODE,VARLIBELLE) values ('3160','EN','Jetta');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (3160,'1',sysdate,null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (3160,1,1,sysdate,'EUR',null,'32000',null,null,'ORFI',null,null);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values ('3160','1','3','GRANDE','vw_jetta_GRANDE.png','PAYSAGE','2015','Exterieur');
