


-------------------------------------------------------
delete from VYEIMAGE where varid > 17000 and varid < 18000;
delete from VYEPRICE where varid > 17000 and varid < 18000;
delete from VARYEAR where varid > 17000 and varid < 18000;
delete from lanvariant where varid > 17000 and varid < 18000;
delete from variant where varid > 17000 and varid < 18000;
delete from lanmakmodtrimlevel where makid = 213;
delete from makmodtrimlevel where makid = 213;
delete from ACAMMO where makid = 213;
delete from lanmakmodel where makid = 213;
delete from makmodel where makid = 213;

-- _E

insert into makmodel(makid, mmocode)  values (213, 'MERC_E');
insert into lanmakmodel values (213, 'MERC_E', 'EN', 'Class E');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'MERC_E', '0');

insert into makmodtrimlevel values(213, 'MERC_E', 'T200D');
insert into lanmakmodtrimlevel values(213, 'MERC_E', 'T200D', 'EN', 'E T200 d');
-- insert into makmodtrimlevel values(213, 'MERC_E', 'SPORT');
-- insert into lanmakmodtrimlevel values(213, 'MERC_E', 'SPORT', 'EN', 'MERC_E Sport');
-- insert into makmodtrimlevel values(213, 'MERC_E', 'TRAIL');
-- insert into lanmakmodtrimlevel values(213, 'MERC_E', 'TRAIL', 'EN', 'MERC_E Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17001,'FR','MERC_ET200D','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_E',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','T200D',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17001, 'EN', 'MERC_E T200D');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17001,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17001,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,117055,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17001,'2015',1,'GRANDE','MERC_E_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17002,'FR','MERC_ESPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_E',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17002, 'EN', 'MERC_E sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17002,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17002,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,24250,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17002,'2015',1,'GRANDE','MERC_MERC_E_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17003,'FR','MERC_ETRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_E',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17003, 'EN', 'MERC_E trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17003,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17003,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,221350,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17003,'2015',1,'GRANDE','MERC_MERC_E_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- _GLS

insert into makmodel(makid, mmocode)  values (213, 'MERC_GLS');
insert into lanmakmodel values (213, 'MERC_GLS', 'EN', 'GLS');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'MERC_GLS', '0');

insert into makmodtrimlevel values(213, 'MERC_GLS', 'GLS350');
insert into lanmakmodtrimlevel values(213, 'MERC_GLS', 'GLS350', 'EN', 'GLS 350 d 4Matic');
-- insert into makmodtrimlevel values(213, 'MERC_GLS', 'SPORT');
-- insert into lanmakmodtrimlevel values(213, 'MERC_GLS', 'SPORT', 'EN', 'MERC_GLS Sport');
-- insert into makmodtrimlevel values(213, 'MERC_GLS', 'TRAIL');
-- insert into lanmakmodtrimlevel values(213, 'MERC_GLS', 'TRAIL', 'EN', 'MERC_GLS Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17011,'FR','MERC_GLSGLS350','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_GLS',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','GLS350',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17011, 'EN', 'GLS 350 d 4Matic');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17011,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17011,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null, 471970,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17011,'2015',1,'GRANDE','MERC_GLS_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17012,'FR','MERC_GLSSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_GLS',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17012, 'EN', 'MERC_GLS sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17012,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17012,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,28230,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17012,'2015',1,'GRANDE','MERC_MERC_GLS_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17013,'FR','MERC_GLSTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_GLS',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17013, 'EN', 'MERC_GLS trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17013,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17013,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,27030,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17013,'2015',1,'GRANDE','MERC_MERC_GLS_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- _SLC

insert into makmodel(makid, mmocode)  values (213, 'MERC_SLC');
insert into lanmakmodel values (213, 'MERC_SLC', 'EN', 'SLC');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'MERC_SLC', '0');

insert into makmodtrimlevel values(213, 'MERC_SLC', 'MERCSLC250D');
insert into lanmakmodtrimlevel values(213, 'MERC_SLC', 'MERCSLC250D', 'EN', 'SLC 250d');
insert into makmodtrimlevel values(213, 'MERC_SLC', 'MERCSL400');
insert into lanmakmodtrimlevel values(213, 'MERC_SLC', 'MERCSL400', 'EN', 'SL 400');
-- insert into makmodtrimlevel values(213, 'MERC_SLC', 'TRAIL');
-- insert into lanmakmodtrimlevel values(213, 'MERC_SLC', 'TRAIL', 'EN', 'MERC_SLC Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17021,'FR','MERC_SLCMERCSLC250D','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_SLC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','MERCSLC250D',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17021, 'EN', 'Mercedes SLC 250d');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17021,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17021,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,605078,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17021,'2015',1,'GRANDE','MERC_SLC_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17022,'FR','MERC_SLCMERCSL400','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_SLC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','MERCSL400',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17022, 'EN', 'Mercedes SL 400');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17022,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17022,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,321340,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17022,'2015',1,'GRANDE','MERC_SL_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17023,'FR','MERC_SLCTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_SLC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17023, 'EN', 'MERC_SLC trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17023,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17023,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,32700,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17023,'2015',1,'GRANDE','MERC_MERC_SLC_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- _S

insert into makmodel(makid, mmocode)  values (213, 'MERC_S');
insert into lanmakmodel values (213, 'MERC_S', 'EN', 'Class S');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'MERC_S', '0');

insert into makmodtrimlevel values(213, 'MERC_S', '40EVU');
insert into lanmakmodtrimlevel values(213, 'MERC_S', '40EVU', 'EN', 'S 500');
-- insert into makmodtrimlevel values(213, 'MERC_S', 'SPORT');
-- insert into lanmakmodtrimlevel values(213, 'MERC_S', 'SPORT', 'EN', 'MERC_S Sport');
-- insert into makmodtrimlevel values(213, 'MERC_S', 'TRAIL');
-- insert into lanmakmodtrimlevel values(213, 'MERC_S', 'TRAIL', 'EN', 'MERC_S Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17031,'FR','MERC_S40EVU','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_S',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','40EVU',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17031, 'EN', 'S 500');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17031,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17031,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,280725,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17031,'2015',1,'GRANDE','MERC_S_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17032,'FR','MERC_SSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_S',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17032, 'EN', 'MERC_S sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17032,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17032,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,129340,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17032,'2015',1,'GRANDE','MERC_MERC_S_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (17033,'FR','MERC_STRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERC_S',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (17033, 'EN', 'MERC_S trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17033,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17033,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,129500,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17033,'2015',1,'GRANDE','MERC_MERC_S_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

/*
-- X6

insert into makmodel(makid, mmocode)  values (213, 'MERCX6');
insert into lanmakmodel values (213, 'MERCX6', 'EN', 'MERC X6');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'MERCX6', '0');

insert into makmodtrimlevel values(213, 'MERCX6', 'LUXURY');
insert into lanmakmodtrimlevel values(213, 'MERCX6', 'LUXURY', 'EN', 'MERCX6 Luxury');
insert into makmodtrimlevel values(213, 'MERCX6', 'SPORT');
insert into lanmakmodtrimlevel values(213, 'MERCX6', 'SPORT', 'EN', 'MERCX6 Sport');
insert into makmodtrimlevel values(213, 'MERCX6', 'TRAIL');
insert into lanmakmodtrimlevel values(213, 'MERCX6', 'TRAIL', 'EN', 'MERCX6 Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17041,'FR','MERCX6LUXURY','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERCX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','LUXURY',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17041, 'EN', 'MERCX6 luxury');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17041,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17041,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,134500,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17041,'2015',1,'GRANDE','MERC_MERCX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17042,'FR','MERCX6SPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERCX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17042, 'EN', 'MERCX6 sport');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17042,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17042,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,133000,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17042,'2015',1,'GRANDE','MERC_MERCX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17043,'FR','MERCX6TRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'MERCX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17043, 'EN', 'MERCX6 trail');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17043,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17043,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,132000,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17043,'2015',1,'GRANDE','MERC_MERCX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');
*/
/*
-- BU10

insert into makmodel(makid, mmocode)  values (213, 'BU10');
insert into lanmakmodel values (213, 'BU10', 'EN', 'BU10');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'213', 'BU10', '0');

insert into makmodtrimlevel values(213, 'BU10', 'LUXURY');
insert into lanmakmodtrimlevel values(213, 'BU10', 'LUXURY', 'EN', 'BU10');
insert into makmodtrimlevel values(213, 'BU10', 'SPORT');
insert into lanmakmodtrimlevel values(213, 'BU10', 'SPORT', 'EN', 'BU10 Sport');
insert into makmodtrimlevel values(213, 'BU10', 'TRAIL');
insert into lanmakmodtrimlevel values(213, 'BU10', 'TRAIL', 'EN', 'BU10 Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (17051,'FR','BU10LUXURY','EUR',to_date('23-MAY-15','DD-MON-RR'),null,213,'BU10',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','LUXURY',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (17051, 'EN', 'BU10 luxury');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (17051,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (17051,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,1129,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (17051,'2015',1,'GRANDE','MERC_BU10_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

*/


