


-------------------------------------------------------
delete from VYEIMAGE where varid > 16000 and varid < 17000;
delete from VYEPRICE where varid > 16000 and varid < 17000;
delete from VARYEAR where varid > 16000 and varid < 17000;
delete from lanvariant where varid > 16000 and varid < 17000;
delete from variant where varid > 16000 and varid < 17000;
delete from lanmakmodtrimlevel where makid = 92;
delete from makmodtrimlevel where makid = 92;
delete from ACAMMO where makid = 92;
delete from lanmakmodel where makid = 92;
delete from makmodel where makid = 92;

-- NEF

insert into makmodel(makid, mmocode)  values (92, 'DMGMNEF');
insert into lanmakmodel values (92, 'DMGMNEF', 'EN', 'DMGM NEF');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'DMGMNEF', '0');

insert into makmodtrimlevel values(92, 'DMGMNEF', 'T400');
insert into lanmakmodtrimlevel values(92, 'DMGMNEF', 'T400', 'EN', 'DMGMNEF T400');
-- insert into makmodtrimlevel values(92, 'DMGMNEF', 'SPORT');
-- insert into lanmakmodtrimlevel values(92, 'DMGMNEF', 'SPORT', 'EN', 'DMGMNEF Sport');
-- insert into makmodtrimlevel values(92, 'DMGMNEF', 'TRAIL');
-- insert into lanmakmodtrimlevel values(92, 'DMGMNEF', 'TRAIL', 'EN', 'DMGMNEF Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16001,'FR','DMGMNEFT400','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMNEF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','T400',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16001, 'EN', 'DMGMNEF T400');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16001,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16001,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,116055,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16001,'2015',1,'GRANDE','DMGM_DMGMNEF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16002,'FR','DMGMNEFSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMNEF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16002, 'EN', 'DMGMNEF sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16002,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16002,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,24250,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16002,'2015',1,'GRANDE','DMGM_DMGMNEF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16003,'FR','DMGMNEFTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMNEF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16003, 'EN', 'DMGMNEF trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16003,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16003,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,29250,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16003,'2015',1,'GRANDE','DMGM_DMGMNEF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- DMF

insert into makmodel(makid, mmocode)  values (92, 'DMGMDMF');
insert into lanmakmodel values (92, 'DMGMDMF', 'EN', 'DMGM DMF');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'DMGMDMF', '0');

insert into makmodtrimlevel values(92, 'DMGMDMF', 'T260');
insert into lanmakmodtrimlevel values(92, 'DMGMDMF', 'T260', 'EN', 'DMGMDMF T260');
-- insert into makmodtrimlevel values(92, 'DMGMDMF', 'SPORT');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMF', 'SPORT', 'EN', 'DMGMDMF Sport');
-- insert into makmodtrimlevel values(92, 'DMGMDMF', 'TRAIL');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMF', 'TRAIL', 'EN', 'DMGMDMF Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16011,'FR','DMGMDMFT260','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','T260',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16011, 'EN', 'DMGMDMF T260');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16011,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16011,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null, 471970,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16011,'2015',1,'GRANDE','DMGM_DMGMDMF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16012,'FR','DMGMDMFSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16012, 'EN', 'DMGMDMF sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16012,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16012,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,28230,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16012,'2015',1,'GRANDE','DMGM_DMGMDMF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16013,'FR','DMGMDMFTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMF',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16013, 'EN', 'DMGMDMF trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16013,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16013,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,27030,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16013,'2015',1,'GRANDE','DMGM_DMGMDMF_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- DMC

insert into makmodel(makid, mmocode)  values (92, 'DMGMDMC');
insert into lanmakmodel values (92, 'DMGMDMC', 'EN', 'DMGM DMC');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'DMGMDMC', '0');

insert into makmodtrimlevel values(92, 'DMGMDMC', 'T60HLINEAR');
insert into lanmakmodtrimlevel values(92, 'DMGMDMC', 'T60HLINEAR', 'EN', 'DMGMDMC 60 H Linear');
-- insert into makmodtrimlevel values(92, 'DMGMDMC', 'SPORT');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMC', 'SPORT', 'EN', 'DMGMDMC Sport');
-- insert into makmodtrimlevel values(92, 'DMGMDMC', 'TRAIL');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMC', 'TRAIL', 'EN', 'DMGMDMC Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16021,'FR','DMGMDMCT60HLINEAR','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','T60HLINEAR',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16021, 'EN', 'DMGMDMC 60 H Linear');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16021,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16021,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,605078,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16021,'2015',1,'GRANDE','DMGM_DMGMDMC_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16022,'FR','DMGMDMCSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16022, 'EN', 'DMGMDMC sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16022,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16022,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,39240,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16022,'2015',1,'GRANDE','DMGM_DMGMDMC_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16023,'FR','DMGMDMCTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMC',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16023, 'EN', 'DMGMDMC trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16023,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16023,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,32700,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16023,'2015',1,'GRANDE','DMGM_DMGMDMC_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- DMU

insert into makmodel(makid, mmocode)  values (92, 'DMGMDMU');
insert into lanmakmodel values (92, 'DMGMDMU', 'EN', 'DMGM DMU');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'DMGMDMU', '0');

insert into makmodtrimlevel values(92, 'DMGMDMU', '40EVU');
insert into lanmakmodtrimlevel values(92, 'DMGMDMU', '40EVU', 'EN', 'DMGMDMU 40eVu');
-- insert into makmodtrimlevel values(92, 'DMGMDMU', 'SPORT');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMU', 'SPORT', 'EN', 'DMGMDMU Sport');
-- insert into makmodtrimlevel values(92, 'DMGMDMU', 'TRAIL');
-- insert into lanmakmodtrimlevel values(92, 'DMGMDMU', 'TRAIL', 'EN', 'DMGMDMU Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16031,'FR','DMGMDMU40EVU','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMU',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','40EVU',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16031, 'EN', 'DMGMDMU 40eVu');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16031,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16031,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,280725,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16031,'2015',1,'GRANDE','DMGM_DMGMDMU_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16032,'FR','DMGMDMUSPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMU',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16032, 'EN', 'DMGMDMU sport');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16032,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16032,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,129340,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16032,'2015',1,'GRANDE','DMGM_DMGMDMU_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

-- Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
-- values (16033,'FR','DMGMDMUTRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMDMU',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
-- insert into LANVARIANT values (16033, 'EN', 'DMGMDMU trail');
-- Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16033,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
-- Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16033,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,129500,null,null,null,null,21);
-- Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16033,'2015',1,'GRANDE','DMGM_DMGMDMU_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

/*
-- X6

insert into makmodel(makid, mmocode)  values (92, 'DMGMX6');
insert into lanmakmodel values (92, 'DMGMX6', 'EN', 'DMGM X6');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'DMGMX6', '0');

insert into makmodtrimlevel values(92, 'DMGMX6', 'LUXURY');
insert into lanmakmodtrimlevel values(92, 'DMGMX6', 'LUXURY', 'EN', 'DMGMX6 Luxury');
insert into makmodtrimlevel values(92, 'DMGMX6', 'SPORT');
insert into lanmakmodtrimlevel values(92, 'DMGMX6', 'SPORT', 'EN', 'DMGMX6 Sport');
insert into makmodtrimlevel values(92, 'DMGMX6', 'TRAIL');
insert into lanmakmodtrimlevel values(92, 'DMGMX6', 'TRAIL', 'EN', 'DMGMX6 Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16041,'FR','DMGMX6LUXURY','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','LUXURY',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16041, 'EN', 'DMGMX6 luxury');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16041,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16041,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,134500,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16041,'2015',1,'GRANDE','DMGM_DMGMX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16042,'FR','DMGMX6SPORT','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','SPORT',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16042, 'EN', 'DMGMX6 sport');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16042,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16042,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,133000,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16042,'2015',1,'GRANDE','DMGM_DMGMX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16043,'FR','DMGMX6TRAIL','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'DMGMX6',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','TRAIL',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16043, 'EN', 'DMGMX6 trail');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16043,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16043,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,132000,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16043,'2015',1,'GRANDE','DMGM_DMGMX6_GRANDE.jpg','PAYSAGE',2015,'Exterieur');
*/
/*
-- BU10

insert into makmodel(makid, mmocode)  values (92, 'BU10');
insert into lanmakmodel values (92, 'BU10', 'EN', 'BU10');

Insert into ACAMMO (ACACODE,MAKID,MMOCODE,AMMFLAGDEFAULT) values ('CAR' ,'92', 'BU10', '0');

insert into makmodtrimlevel values(92, 'BU10', 'LUXURY');
insert into lanmakmodtrimlevel values(92, 'BU10', 'LUXURY', 'EN', 'BU10');
insert into makmodtrimlevel values(92, 'BU10', 'SPORT');
insert into lanmakmodtrimlevel values(92, 'BU10', 'SPORT', 'EN', 'BU10 Sport');
insert into makmodtrimlevel values(92, 'BU10', 'TRAIL');
insert into lanmakmodtrimlevel values(92, 'BU10', 'TRAIL', 'EN', 'BU10 Trail');

Insert into VARIANT (VARID,PAYCODE,VARCODE,DEVCODE,VARDTSTART,VARDTEND,MAKID,MMOCODE,VARVEHICLESECTOR,VARDRIVETRAIN,VARFUELDELIVERY,VARTRANSMISSION,VARNBDOORS,VARSERVICEDISTANCEUNIT,VARSERVICEDISTANCEINTERVAL,VARSERVICETIMEINTERVAL,VARMOTCLASS,VARTAXCLASS,VARVEHICLECATEGORY,VARVEDCLASS,VARENERGYTYPE,VARBODYTYPE,VARBHP,VARCOMMENT,VARSTATUS,MMTCODE,VARBADGEDENGINESIZE,VARUPDATEDATE,VARCARBON,VARIDSOURCE,VARSOURCEDATABASE,VARINSURANCE,VARPRODUCTIONSTARTYEAR,ACACODE,NAPCODE,UTICODEUPDATE,VARDTUPDATE,VAREXTERNALREF) 
values (16051,'FR','BU10LUXURY','EUR',to_date('23-MAY-15','DD-MON-RR'),null,92,'BU10',null,null,'G','A',null,null,null,null,null,'3','VP','03','G','COUP',150,null,'ACTIF','LUXURY',null,to_date('23-MAY-15','DD-MON-RR'),119,null,null,null,2015,'','','ORFI',to_date('23-MAY-15','DD-MON-RR'),null);
insert into LANVARIANT values (16051, 'EN', 'BU10 luxury');
Insert into VARYEAR (VARID,VYEYEARCODE,VYEDTSTART,VYEDTEND,VYEINSURANCE) values (16051,'2015',to_date('01-JAN-15','DD-MON-RR'),null,null);
Insert into VYEPRICE (VARID,VYEYEARCODE,VPRORDER,VPRDTSTART,DEVCODE,VPRDTEND,VPRMT,VPRCODE,VPRDTUPDATE,UTICODEUPDATE,TAXCODE,VPRMTVAT) values (16051,'2015',1,to_date('01-JAN-15','DD-MON-RR'),'EUR',null,1129,null,null,null,null,21);
Insert into VYEIMAGE (VARID,VYEYEARCODE,VYIORDER,VYICATEGORY,VYIFILENAME,VYIORIENTATION,VYIMODELYEAR,VYIVIEWTYPE) values (16051,'2015',1,'GRANDE','DMGM_BU10_GRANDE.jpg','PAYSAGE',2015,'Exterieur');

*/


